#!/bin/bash


echo "Migrando dados do MySQL para fixture..."

python manage.py load_adapted_fixture \
--fixture mysql_fixture.json \
--mapping mysql_to_models_mapping.json \
--order "administradoracondominios,administracaocondominios" \
--disable-constraints \
--clear