# Generated by Django 5.2 on 2025-04-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='origem',
            field=models.CharField(default='', help_text='Origem do boleto.', max_length=255, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='pasta',
            field=models.IntegerField(default=0, unique=True, verbose_name='Número da Pasta'),
            preserve_default=False,
        ),
    ]
