# Generated by Django 5.2 on 2025-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_boleto_origem_boleto_pasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='unidade',
        ),
        migrations.AddField(
            model_name='boleto',
            name='endereco',
            field=models.CharField(default='', help_text='Endereço do boleto.', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='id_migracao',
            field=models.IntegerField(blank=True, help_text='ID único para acompanhamento de migrações', null=True, unique=True, verbose_name='ID de migração'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('vencido', 'Vencido'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('a vencer', 'A Vencer')], default='vencido', max_length=10, verbose_name='Status'),
        ),
    ]
