# Generated by Django 5.2 on 2025-04-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_remove_boleto_unidade_boleto_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='id_migracao',
        ),
    ]
