# Generated by Django 5.2 on 2025-04-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('quantidade_imoveis', models.IntegerField(default=0, verbose_name='Quantidade de Imóveis')),
            ],
            options={
                'verbose_name': 'Administradora',
                'verbose_name_plural': 'Administradoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Condomínio')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Imóvel')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('administradora', models.ForeignKey(help_text='Refere-se à administradora responsável por esse condomínio.', on_delete=django.db.models.deletion.CASCADE, related_name='condominios', to='imoveis.administradora', verbose_name='Administradora da qual o condomínio faz parte')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('bloco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco')),
                ('unidade', models.IntegerField(verbose_name='Número da Unidade')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('pasta', models.IntegerField(unique=True, verbose_name='Número da Pasta')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Login')),
                ('senha', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('condominio', models.ForeignKey(help_text='Refere-se à unidade responsável por esse condomínio.', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='imoveis.condominio', verbose_name='Condomínio da qual a unidade faz parte')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['condominio', 'unidade'],
            },
        ),
    ]
