# Generated by Django 5.2 on 2025-04-10 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
        ('utils', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradora',
            name='quantidade_imoveis',
        ),
        migrations.AddField(
            model_name='administradora',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradora', to='utils.basemodelendereco'),
        ),
    ]
