# Generated by Django 5.2 on 2025-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_administradora_cep_administradora_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradora',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='administradora',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='administradora',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='administradora',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='complemento',
        ),
        migrations.AddField(
            model_name='administradora',
            name='id_migracao',
            field=models.IntegerField(blank=True, help_text='ID único para acompanhamento de migrações', null=True, unique=True, verbose_name='ID de migração'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='id_migracao',
            field=models.IntegerField(blank=True, help_text='ID único para acompanhamento de migrações', null=True, unique=True, verbose_name='ID de migração'),
        ),
    ]
