# Generated by Django 5.2 on 2025-04-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_remove_administradora_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradora',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
    ]
