# Generated by Django 5.2 on 2025-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_alter_administradora_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
    ]
