# Generated by Django 5.2 on 2025-04-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_alter_condominio_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='administradora',
        ),
        migrations.AddField(
            model_name='condominio',
            name='administradoracondominio_id',
            field=models.IntegerField(default=0, help_text='ID da administradora a qual o condomínio faz parte', verbose_name='ID da administradora'),
            preserve_default=False,
        ),
    ]
