# Generated by Django 5.2 on 2025-04-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_remove_condominio_administradora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='condominio',
        ),
        migrations.AddField(
            model_name='unidade',
            name='administracaocondominio_id',
            field=models.IntegerField(default=0, help_text='ID do condomínio a qual a Unidade faz parte', verbose_name='ID do condomínio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidade',
            name='id_migracao',
            field=models.IntegerField(blank=True, help_text='ID único para acompanhamento de migrações', null=True, unique=True, verbose_name='ID de migração'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='proprietario_documento',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Documento do Proprietário'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='proprietario_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Proprietário'),
        ),
    ]
