# Generated by Django 5.2 on 2025-04-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_update_relationships'),
        ('imoveis', '0010_remove_administradora_id_migracao_and_more'),
    ]

    operations = [
    ]
