# Generated by Django 5.2 on 2025-04-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0011_merge_20250410_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='condominio',
            field=models.ForeignKey(blank=True, help_text='Refere-se ao condomínio ao qual esta unidade pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='imoveis.condominio', verbose_name='Condomínio da qual a unidade faz parte'),
        ),
    ]
