# Generated by Django 5.2 on 2025-04-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0012_alter_unidade_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='pasta',
            field=models.CharField(max_length=20),
        ),
    ]
