# Generated by Django 5.2 on 2025-04-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0013_alter_unidade_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='pasta',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número da Pasta'),
        ),
    ]
