# Generated by Django 5.2 on 2025-04-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0014_alter_unidade_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='unidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Unidade'),
        ),
    ]
