# Generated by Django 5.2 on 2025-04-08 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemessaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('arquivo_remessa', models.FileField(blank=True, null=True, upload_to='remessas/', verbose_name='Arquivo de Remessa')),
                ('arquivo_retorno', models.FileField(blank=True, null=True, upload_to='retornos/', verbose_name='Arquivo de Retorno')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remessas_bancarias', to='imoveis.administradora', verbose_name='Administradora')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remessas_bancarias', to='imoveis.condominio', verbose_name='Condomínio')),
            ],
            options={
                'verbose_name': 'Remessa Bancária',
                'verbose_name_plural': 'Remessas Bancárias',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RemessaBancariaBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remessas', to='monitoramento.boleto', verbose_name='Boleto')),
                ('remessa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='financeiro.remessabancaria', verbose_name='Remessa')),
            ],
            options={
                'verbose_name': 'Boleto da Remessa',
                'verbose_name_plural': 'Boletos da Remessa',
                'ordering': ['-criado_em'],
                'unique_together': {('remessa', 'boleto')},
            },
        ),
    ]
